/* File auto-generated by @typed/compiler */
import { makeServerWindow, type ServerWindowOptions } from "@typed/framework/makeServerWindow";


export const assetDirectory: string = '../client'

export const docType: string = `<!DOCTYPE html>`

export const htmlAttributes: Record<string, string> = {"lang":"en-us"}

export const basePath: string = '/'

export const html: string = `<head>
  <title>@typed/fp starter</title>
  <meta charset="utf-8">
  <meta content="@typed/fp starter" name="description">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <script crossorigin src="/assets/index-d4667292.js" type="module"></script>
  <base href="/">
</head>

<body>
  <div id="application"></div>

  
</body>`

export function makeWindow(options: ServerWindowOptions): ReturnType<typeof makeServerWindow> {
  const win = makeServerWindow(options)
  const documentElement = win.document.documentElement

  documentElement.innerHTML = html

  for (const [key, value] of Object.entries(htmlAttributes)) {
    documentElement.setAttribute(key, value)
  }

  return win
}