/* File auto-generated by @typed/compiler */
import { buildModules, Module } from "@typed/framework";
import * as typedModule0 from "./routes/index.js";
import { constant } from "@fp-ts/core/Function";

export const modules = [
  Module.make(typedModule0.route, constant(typedModule0.main))
] as const

export const matcher = buildModules(modules)

export const fallback = null