/* File auto-generated by @typed/compiler */
import { buildModules, Module, runMatcherWithFallback, provideBrowserIntrinsics } from "@typed/framework";
import * as typedModule0 from "./routes/index.js";
import { constant, pipe } from "@fp-ts/core/Function";
import { renderInto } from "@typed/html";
import type * as Fx from "@typed/fx";

export const modules = [
  Module.make(typedModule0.route, constant(typedModule0.main))
] as const

export const matcher = buildModules(modules)

export const fallback = null

export const render = <T extends HTMLElement>(parentElement: T): Fx.Fx<never, never, T> => pipe(runMatcherWithFallback(matcher, fallback), renderInto(parentElement), provideBrowserIntrinsics(window, { parentElement }))